name: "delete-workflow-runs"
author: "Christos Galanopoulos"
description: "Delete the workflow runs for a given repository"
inputs:
  owner:
    description: "Specify the repository owner"
    required: true
  repo:
    description: "Specify the repository name"
    required: true
  token:
    description: "Specify the token used to get and delete the workflow runs"
    required: true
  workflow:
    description: "Specify the workflow name to delete the runs for"
    default: "all"
    required: false
branding:
  icon: delete
  color: gray-dark
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        OWNER: ${{ inputs.owner }}
        REPO: ${{ inputs.repo }}
        TOKEN: ${{ inputs.token }}
        WORKFLOW: ${{ inputs.workflow }}
      run: |
        ${{ github.action_path }}/delete_workflows_runs.sh \
          -o ${{ env.OWNER }} \
          -r ${{ env.REPO }} \
          -t ${{ env.TOKEN }} \
          -w ${{ env.WORKFLOW }}
